port: 8000
meta:
  title: Deno Blog
  description: Deno Blog is a simple blog written in Deno.
log:
  appenders:
    dateFile:
      filename: logs/deno
      daysToKeep: 10
      pattern: yyyy-MM-dd.log
  categories:
    default:
      appenders:
        - dateFile
        - console
      level: DEBUG
